name: plugin-c-hash
version: 1.0.0
description: "A C plugin for computing various hash functions"
author: "ARO Team"
license: MIT
aro-version: ">=0.1.0"

source:
  git: "git@github.com:arolang/plugin-c-hash.git"
  ref: "main"

provides:
  - type: c-plugin
    path: src/
    build:
      compiler: clang
      flags:
        - "-O2"
        - "-fPIC"
        - "-shared"
      output: libhash_plugin.dylib
    actions:
      - name: Hash
        role: own
        verbs: [hash, digest]
        prepositions: [from, with]
        description: Compute simple hash (32-bit)
      - name: DJB2
        role: own
        verbs: [djb2]
        prepositions: [from]
        description: Compute DJB2 hash (64-bit)
      - name: FNV1a
        role: own
        verbs: [fnv1a, fnv]
        prepositions: [from]
        description: Compute FNV-1a hash (64-bit)
